name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout reposistory
      uses: actions/checkout@master
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Get Packages
      run: sudo apt-get install libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev libnfs-dev libiscsi-dev -y
    - name: Build Qemu
      run: mkdir -p qemu/build ;
           cd qemu/build ;
           pwd;
           ../configure --disable-git-update --enable-debug &&
           make
    - name: Upload a QEMU Build Artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: QEMU Native Build
        path: qemu/build/*
