name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout reposistory
      uses: actions/checkout@master
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Build PEMU
      run: sudo chmod +x builder_linux.sh ; sudo ./builder_linux.sh
    - name: Record State
      run: ls -laR
    - name: Upload a PEMU Pin Build Artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: PEMU Pin Build
        path: plugins/build/*
    - name: Upload a QEMU Build Artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: QEMU Build
        path: qemu/build/*
    - name: Upload a LINUX.c Build Artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: Custom PEMU Linux
        path: linux.c
    - name: Upload custom Linux Kernel Build
      uses: actions/upload-artifact@v2.2.1
      with:
        name: Custom PEMU Linux Kernel
        path: buildroot/output/images/*
